#!/bin/bash
export PWD="$(
  cd "$(dirname "$0")"
  pwd -P
)"

# Set the correct theme.toml config
leftwm-command "LoadTheme $PWD/theme.toml"

#  Down any previous running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
  /tmp/leftwm-theme-down
  rm /tmp/leftwm-theme-down
fi
ln -s ${PWD}/down /tmp/leftwm-theme-down

# Boot Picom if it exists
if [ -x "$(command -v picom)" ]; then
  picom &>/dev/null &
fi

# Restore desktop wallpaper(s)
nitrogen --restore
#if [ -x "$(command -v feh)" ]; then
#feh --bg-scale "${PWD}/background.png"
#  feh --bg-scale "$(cat ~/.background)"
#fi

# extra utils to make this theme a little more homey
if [ -x "$(command -v dunst)" ]; then
  dunst -config ~/.config/dunst/dunstrc &
fi

# launch network-manager applet, but only if it's not already running
if [ -x "$(command -v nm-applet)"]; then
  ps aux | grep nm-applet | grep -v grep >/dev/null || nm-applet &
fi

#boot a polybar for each monitor
cd ${PWD}/polybar
polybar -m | sed s/:.*// | tac | while read -r monitor; do
  monitor=$monitor polybar -c config.ini main &>/tmp/polybar.log &
done
